---
- hosts: all
  become: yes
  tasks:
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest  
  - name: Download python
    apt:
      name: python
      state: present
  - name: install wget
    apt:
      name: wget
      state: present
  - name: install openjdk
    become: yes
    apt:
      name: openjdk-8-jdk
      state: present

  - name: Installing Key
    shell: wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -

  - name: Add the Jenkins repository to the system
    become: yes
    shell: sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'       

  - name: Updating apt-get cache again
    apt: 
      update_cache: yes

  - name: Installing Jenkins Only
    apt:
      name: jenkins
      state: present 
  - name: Sleep for 30 seconds and continue with play
    wait_for: timeout=30

  - name: Get init password Jenkins
    shell: cat /var/lib/jenkins/secrets/initialAdminPassword
    changed_when: false
    register: result
  
  - debug:
     msg: var=result    
    
  handlers:
    - name: restart
      service: 
        name: jenkins
        state: restart



